### ISSUE TITLE
sulu Resourcelocator does not works properly

### ISSUE THREAD

**Issue by Kharestani** [sulu/sulu-standard#698]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | developer |
| Browser Version | All |
#### Actual Behavior

In the admin section when I wanted to add a content in persian (it is a RTL language and works under UTF8-without_BOM ) sulu Resourcelocator  could not be generated and counted the persian title as a empty title it also goes for arabic, hebrew and mandarin Chinese but it works fine and also it does not have a problem for mandarin Chinese; even when I entered the Resourcelocator manually it had counted as empty string and did not let me to publish the form at all.
#### Expected Behavior

It should add '-' for spaces and cover all languages. ;D
#### Possible Solutions

I thought it might be the php files encoding but as long as I checked I could not find the problem yet.

Thank you all

**Comment by wachterjohannes** [comment]
could you please paste an example here? i will try it locally to find the issue. maybe the replacers for this language are missing.

**Comment by Kharestani** [comment]
you can try for persian or arabic with: `تیتر متن` and for hebrew with: `Εβραϊκή γλώσσα` and for mandarin Chinese with `官 話`.
Thanks

**Comment by wachterjohannes** [comment]
i have talked to @c00n84 we will generate an empty resource-locator and give the user a message that he should type-in a correct one. /cc @chirimoya should we include that in a HOTFIX?

**Comment by Kharestani** [comment]
I think there is a problem in husky.js or something in that area cause the form validator does not validate  these kind of languages as well, to me it seems look like the forms use that for validation; am i right?

**Comment by wachterjohannes** [comment]
i have created a PR which should fix this issue (at least in the backend) https://github.com/sulu/sulu/pull/2400

It will give you empty resource-locators and if you type in a correct one you can save the node normally.

**Comment by Kharestani** [comment]
I think it does not make the problem go away; I still have the error with form validation in which it counts the `Resourcelocator` as an empty field. we need to go to `husky.js` to solve the problem.

**Comment by wachterjohannes** [comment]
hmm the field is empty yes but the user has to fill in the resource-locator. it cannot be empty when you want to save.

**Comment by Kharestani** [comment]
even when I add text manually the validator count it as empty.

**Comment by Kharestani** [comment]
![image](https://cloud.githubusercontent.com/assets/5319248/15361588/5765a094-1d27-11e6-9df1-4c46ec2d033a.png)
it is still red even when I added text

**Comment by wachterjohannes** [comment]
this resource-locator is not valid you have to type in latin letters

**Comment by Kharestani** [comment]
ok i know but how can I use internationalizing system to make it work with languages other than latin?
like : `%E5%BC%95%E3%81%8D%E5%89%B2%E3%82%8A`

**Comment by Kharestani** [comment]
I think the problem comes from `\vendor\sulu\sulu\src\Sulu\Bundle\ContentBundle\Resources\public\js\validation\types\resourceLocator.js`

**Comment by wachterjohannes** [comment]
yes the front-end validation. but we have a deeper problem. our url storage (phpcr) cannot use arababic letters for "nodeName" and thats why we ignore them everywhere

**Comment by Kharestani** [comment]
See `Internationalized URL`  on  http://en.m.wikipedia.org/wiki/Uniform_Resource_Locator it could help

**Comment by danrot** [comment]
@wachterjohannes Where have you got that information from? I mean that PHPCR cannot use arabic letters? I just created a node named like that:
![image](https://cloud.githubusercontent.com/assets/405874/15384249/688d4fa8-1d99-11e6-8264-6c6364103458.png)

**Comment by wachterjohannes** [comment]
hmm there were an exception when i tried it from a raw php file ... maybe there was another issue. then maybe another slugifier would be enough. our current one removes this letters. see https://github.com/aferrandini/Urlizer/blob/master/Urlizer.php

**Comment by Kharestani** [comment]
Ok something I discovered just now! when I tried to make a sulu-standard with webspace settings like :
```xml
<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.0.xsd">

    <name>tcbase.io</name>
    <key>tcbase_io</key>

    <localizations>
        <localization language="fa" default="true"/>
        <localization language="en"/>
    </localizations>

    <theme>
        <key>default</key>
        <default-templates>
            <default-template type="page">default</default-template>
            <default-template type="homepage">overview</default-template>
        </default-templates>

        <error-templates>
            <error-template default="true">ClientWebsiteBundle:views:error.html.twig</error-template>
            <error-template code="404">ClientWebsiteBundle:views:error404.html.twig</error-template>
        </error-templates>
    </theme>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="fa">Mainnavigation</title>
                    <title lang="en">Mainnavigation</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>tcbase.io</name>
            <key>tcbase_io</key>
            <resource-locator>
                <strategy>tree</strategy>
            </resource-locator>

            <environments>
                <environment type="prod">
                    <urls>
                        <url>{host}/{localization}</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url>{host}/{localization}</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url>{host}/{localization}</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>
```
the content part and the home page part in admin panel do not work due to errors from `husky.js`
It seems when I did `app/console sulu:build prod` and `app/console sulu:build dev` stuff got made in persian from symfony translations (like the homepage name) and `husky.js` exactly has problem with the  resource-locator part of the page here too. I checked it.

**Comment by danrot** [comment]
@Kharestani Can you check the path `/cmf/tcbase_io/contents` with the `doctrine:phpcr:shell` command, and see if there are any arabic letters? Maybe also post the output in here. AFAIK the generated title of the homepage at the beginning is not translated, so this should not be the issue.

In case you want to dive deeper into husky because of this issue, you should check the [husky repository](https://github.com/massiveart/husky), which also contains the code not being built yet 😉

**Comment by alexander-schranz** [comment]
@Kharestani @danrot is the localization part in the portal not required? And in which languages the meta need to be I only did use backend language their ('en', 'de') not the webspace languages.

**Comment by Kharestani** [comment]
@danrot It seems you are right. I run this:
`php app/console doctrine:phpcr:shell "node:list /cmf/tcbase_io/contents"`
and I got this:
```
/cmf/tcbase_io/contents [nt:unstructured] > nt:base
+----------------------------+-------------+--------------------------------------+
| jcr:primaryType            | NAME (15)   | nt:unstructured                      |
| jcr:mixinTypes             | NAME (9)    | [0] sulu:home                        |
| jcr:uuid                   | STRING (36) | 5dd4ca1b-7c72-473f-b930-acb44a59af68 |
| i18n:fa-title              | STRING (8)  | Homepage                             |
| i18n:fa-url                | STRING (1)  | /                                    |
| i18n:fa-smartcontent       | STRING (4)  | null                                 |
| i18n:fa-template           | STRING (8)  | overview                             |
| i18n:fa-navContexts        | STRING (0)  |                                      |
| i18n:fa-nodeType           | LONG (1)    | 1                                    |
| i18n:fa-state              | LONG (1)    | 2                                    |
| i18n:fa-published          | DATE (29)   | 2016-05-20T17:03:24+02:00            |
| sulu:order                 | LONG (2)    | 30                                   |
| i18n:fa-created            | DATE (29)   | 2016-05-20T17:03:24+02:00            |
| i18n:fa-changed            | DATE (29)   | 2016-05-20T17:03:24+02:00            |
| i18n:en-seo-title          | STRING (0)  |                                      |
| i18n:en-seo-description    | STRING (0)  |                                      |
| i18n:en-seo-keywords       | STRING (0)  |                                      |
| i18n:en-seo-canonicalUrl   | STRING (0)  |                                      |
| i18n:en-seo-noIndex        | BOOLEAN (0) | false                                |
| i18n:en-seo-noFollow       | BOOLEAN (0) | false                                |
| i18n:en-seo-hideInSitemap  | BOOLEAN (0) | false                                |
| i18n:en-excerpt-categories | STRING (0)  |                                      |
| i18n:en-excerpt-tags       | STRING (0)  |                                      |
| i18n:en-excerpt-icon       | STRING (2)  | []                                   |
| i18n:en-excerpt-images     | STRING (2)  | []                                   |
| i18n:en-title              | STRING (8)  | Homepage                             |
| i18n:en-url                | STRING (1)  | /                                    |
| i18n:en-smartcontent       | STRING (4)  | null                                 |
| i18n:en-template           | STRING (8)  | overview                             |
| i18n:en-navContexts        | STRING (0)  |                                      |
| i18n:en-nodeType           | LONG (1)    | 1                                    |
| i18n:en-state              | LONG (1)    | 2                                    |
| i18n:en-published          | DATE (29)   | 2016-05-20T17:03:24+02:00            |
| i18n:en-created            | DATE (29)   | 2016-05-20T17:03:24+02:00            |
| i18n:en-changed            | DATE (29)   | 2016-05-20T17:03:24+02:00            |
| i18n:de-seo-title          | STRING (0)  |                                      |
| i18n:de-seo-description    | STRING (0)  |                                      |
| i18n:de-seo-keywords       | STRING (0)  |                                      |
| i18n:de-seo-canonicalUrl   | STRING (0)  |                                      |
| i18n:de-seo-noIndex        | BOOLEAN (0) | false                                |
| i18n:de-seo-noFollow       | BOOLEAN (0) | false                                |
| i18n:de-seo-hideInSitemap  | BOOLEAN (0) | false                                |
| i18n:de-excerpt-categories | STRING (0)  |                                      |
| i18n:de-excerpt-tags       | STRING (0)  |                                      |
| i18n:de-excerpt-icon       | STRING (2)  | []                                   |
| i18n:de-excerpt-images     | STRING (2)  | []                                   |
| i18n:de-url                | STRING (1)  | /                                    |
| i18n:de-smartcontent       | STRING (2)  | []                                   |
| i18n:de-template           | STRING (8)  | overview                             |
| i18n:de-navContexts        | STRING (0)  |                                      |
| i18n:de-nodeType           | LONG (1)    | 1                                    |
| i18n:de-state              | LONG (1)    | 2                                    |
| i18n:de-published          | DATE (29)   | 2016-05-20T17:32:50+02:00            |
| i18n:de-created            | DATE (29)   | 2016-05-20T17:03:24+02:00            |
| i18n:de-changed            | DATE (29)   | 2016-05-20T17:32:50+02:00            |
+----------------------------+-------------+--------------------------------------+
1 nodes in set (0.000000 sec)
```
and there is no `i18n:de-title` could that be the problem?

**Comment by danrot** [comment]
@alexander-schranz No, the localizations in the portal are optional. When you omit them, all the localizations of this workspace are taken. But you are right about the meta tags, they should contain translations from the system locales, not from the webspaces ones. This is because these tags are only used in the UI, which is only translated in the system locales.

@Kharestani Yeah, that's interesting... Actually there shouldn't be any properties prefixed with `i18n:de-`, because `de` is not a localization in your webspace. Maybe these properties are orphans? Can you try to delete everything (`app/console sulu:build dev --destroy`, but do that only if you haven't any important data in Sulu, since everything will be lost)?

**Comment by Kharestani** [comment]
sorry for the delay.
after I ran `app/console sulu:build dev --destroy` I tried `php app/console doctrine:phpcr:shell "node:list /cmf/tcbase_io/contents"` again and for en as default language the result was:
```
/cmf/tcbase_io/contents [nt:unstructured] > nt:base
+----------------------------+-------------+--------------------------------------+
| jcr:primaryType            | NAME (15)   | nt:unstructured                      |
| jcr:mixinTypes             | NAME (9)    | [0] sulu:home                        |
| jcr:uuid                   | STRING (36) | f0e68b74-dd3b-4475-bd9b-8df8158f3d57 |
| i18n:en-title              | STRING (8)  | Homepage                             |
| i18n:en-url                | STRING (1)  | /                                    |
| i18n:en-smartcontent       | STRING (4)  | null                                 |
| i18n:en-template           | STRING (8)  | overview                             |
| i18n:en-navContexts        | STRING (0)  |                                      |
| i18n:en-nodeType           | LONG (1)    | 1                                    |
| i18n:en-state              | LONG (1)    | 2                                    |
| i18n:en-published          | DATE (29)   | 2016-06-04T19:56:47+02:00            |
| sulu:order                 | LONG (2)    | 30                                   |
| i18n:en-created            | DATE (29)   | 2016-06-04T19:56:47+02:00            |
| i18n:en-changed            | DATE (29)   | 2016-06-04T19:56:47+02:00            |
| i18n:fa-seo-title          | STRING (0)  |                                      |
| i18n:fa-seo-description    | STRING (0)  |                                      |
| i18n:fa-seo-keywords       | STRING (0)  |                                      |
| i18n:fa-seo-canonicalUrl   | STRING (0)  |                                      |
| i18n:fa-seo-noIndex        | BOOLEAN (0) | false                                |
| i18n:fa-seo-noFollow       | BOOLEAN (0) | false                                |
| i18n:fa-seo-hideInSitemap  | BOOLEAN (0) | false                                |
| i18n:fa-excerpt-categories | STRING (0)  |                                      |
| i18n:fa-excerpt-tags       | STRING (0)  |                                      |
| i18n:fa-excerpt-icon       | STRING (2)  | []                                   |
| i18n:fa-excerpt-images     | STRING (2)  | []                                   |
| i18n:fa-title              | STRING (8)  | Homepage                             |
| i18n:fa-url                | STRING (1)  | /                                    |
| i18n:fa-smartcontent       | STRING (4)  | null                                 |
| i18n:fa-template           | STRING (8)  | overview                             |
| i18n:fa-navContexts        | STRING (0)  |                                      |
| i18n:fa-nodeType           | LONG (1)    | 1                                    |
| i18n:fa-state              | LONG (1)    | 2                                    |
| i18n:fa-published          | DATE (29)   | 2016-06-04T19:56:50+02:00            |
| i18n:fa-created            | DATE (29)   | 2016-06-04T19:56:47+02:00            |
| i18n:fa-changed            | DATE (29)   | 2016-06-04T19:56:50+02:00            |
+----------------------------+-------------+--------------------------------------+
1 nodes in set (0.000000 sec)
```
and for `fa` as the default language the result was:
```
+----------------------------+-------------+--------------------------------------+
| jcr:primaryType            | NAME (15)   | nt:unstructured                      |
| jcr:mixinTypes             | NAME (9)    | [0] sulu:home                        |
| jcr:uuid                   | STRING (36) | b3f80bf6-a5c2-4e8e-9b02-62b0f375fd8e |
| i18n:fa-title              | STRING (8)  | Homepage                             |
| i18n:fa-url                | STRING (1)  | /                                    |
| i18n:fa-smartcontent       | STRING (4)  | null                                 |
| i18n:fa-template           | STRING (8)  | overview                             |
| i18n:fa-navContexts        | STRING (0)  |                                      |
| i18n:fa-nodeType           | LONG (1)    | 1                                    |
| i18n:fa-state              | LONG (1)    | 2                                    |
| i18n:fa-published          | DATE (29)   | 2016-06-04T20:04:05+02:00            |
| sulu:order                 | LONG (2)    | 30                                   |
| i18n:fa-created            | DATE (29)   | 2016-06-04T20:04:05+02:00            |
| i18n:fa-changed            | DATE (29)   | 2016-06-04T20:04:05+02:00            |
| i18n:en-seo-title          | STRING (0)  |                                      |
| i18n:en-seo-description    | STRING (0)  |                                      |
| i18n:en-seo-keywords       | STRING (0)  |                                      |
| i18n:en-seo-canonicalUrl   | STRING (0)  |                                      |
| i18n:en-seo-noIndex        | BOOLEAN (0) | false                                |
| i18n:en-seo-noFollow       | BOOLEAN (0) | false                                |
| i18n:en-seo-hideInSitemap  | BOOLEAN (0) | false                                |
| i18n:en-excerpt-categories | STRING (0)  |                                      |
| i18n:en-excerpt-tags       | STRING (0)  |                                      |
| i18n:en-excerpt-icon       | STRING (2)  | []                                   |
| i18n:en-excerpt-images     | STRING (2)  | []                                   |
| i18n:en-title              | STRING (8)  | Homepage                             |
| i18n:en-url                | STRING (1)  | /                                    |
| i18n:en-smartcontent       | STRING (4)  | null                                 |
| i18n:en-template           | STRING (8)  | overview                             |
| i18n:en-navContexts        | STRING (0)  |                                      |
| i18n:en-nodeType           | LONG (1)    | 1                                    |
| i18n:en-state              | LONG (1)    | 2                                    |
| i18n:en-published          | DATE (29)   | 2016-06-04T20:04:05+02:00            |
| i18n:en-created            | DATE (29)   | 2016-06-04T20:04:05+02:00            |
| i18n:en-changed            | DATE (29)   | 2016-06-04T20:04:05+02:00            |
+----------------------------+-------------+--------------------------------------+
1 nodes in set (0.000000 sec)
```
and when I tried to save a content with Persian Title there was another error from husky but I was able to save a content with english title and persian body.

**Comment by wachterjohannes** [comment]
thats what i have fixed in the linked PR. there you could use persian title, persion content but the resource-locator would have to be english. would that help you? (for the moment)

**Comment by wachterjohannes** [comment]
i have also found a quite good slugify library. https://github.com/cocur/slugify

**Comment by Kharestani** [comment]
@wachterjohannes Yes sure, that can solve the problem for now but we should make it right for future.

**Comment by wachterjohannes** [comment]
@danrot what do you think?

**Comment by danrot** [comment]
Using an external slugifier sounds like a good solution to me. The problem with the linked PR for me is that it names the node after the UUID, and I am not sure if this has some unwanted side effects...

**Comment by ibnab** [comment]
Same problem in article bundle too , sulu don't accept arabic  with some character in url - routePah - and some time not saved in title

**Comment by wachterjohannes** [comment]
@ibnab tbh there was no progress about this topic but last weeks we have discussed it and it will maybe be fixed in 2.0 - its not that easy :)

**Comment by ibnab** [comment]
I have used https://github.com/cocur/slugify by provided the service sulu_document_manager.node_name_slugifier , and is work perfect for arabic , So good idea for small patch before lunching the V2

**Comment by oknemi** [comment]
@ibnab 
Please, could you describe your method of replacing the service?

**Comment by danrot** [comment]
Closing in favour of sulu/sulu#3367, because it is in the correct repository.
